### ISSUE TITLE
add contribution instruction to readme

### ISSUE THREAD

**Issue by mahf708** [E3SM-Project/containers#4]
and also include contribution file?

--

The docs will indicate the following:

we want to have a distinct style, probably only some important elements --- for a "xyz" container

- name: containers-xyz
- folder: xyz
- versions: xyz-1.2.3

and the github action workflow will act only on the folder and itself.

**Comment by bartgol** [comment]
You mean to the root folder readme? Or inside the container subfolder? I assume the latter.

**Comment by mahf708** [comment]
The details above are going to be for generic instructions, I edited the main post. Essentially, I think we want to have a style spelled out, so that people know ahead of time our expectation for contribution:

--

The docs will indicate the following:

we want to have a distinct style, probably only some important elements --- for a "xyz" container

name: containers-xyz
folder: xyz
versions: xyz-1.2.3
and the github action workflow will act only on the folder and itself.
